security:
  password_hashers:
    App\Entity\Member: 'auto'

  providers:
    app_member_provider:
      entity:
        class: App\Entity\Member
        property: email   # login = email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_member_provider

      # Form login classique
      form_login:
        login_path: app_login
        check_path: app_login
        enable_csrf: true
        # après login, on redirige vers /me (qui redirigera vers la fiche du membre courant)
        default_target_path: app_me

      logout:
        path: app_logout
        target: app_login

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER

  access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/admin, roles: ROLE_ADMIN }
    # (le reste sera accessible, on affinera plus tard avec #[IsGranted] côté contrôleurs si besoin)
